[package]
name = "nft-benefits-depositary"
version = "0.0.0"
authors = ["Pavel Iakushin <piakushin@roke.to>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0"
near-contract-standards = "4.0"
serde = "1.0"
