[package]
name = "nft-benefits-vault"
version = "0.0.0"
authors = ["Pavel Iakushin <piakushin@roke.to>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[dependencies]
near-sdk = "*"
near-contract-standards = "*"
near-primitives = "=0.14.0"

[dev-dependencies]
tokio = { version = "*", features = ["macros", "rt"] }
anyhow = "*"
workspaces = "0.5.0"
near-primitives = "=0.14.0"